title:              Dave
tagline:            on GitHub Pages
description:        Miscellaneous, mostly work related notes.
url:                http://datadavev.github.io

author:
  name:             Dave Vieglais
  url:              https://ku.edu/~vieglais
  email:            dave.vieglais@gmail.com

# GitHub Pages / Jekyll configuration
markdown: kramdown
kramdown:
  input: GFM
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
