title:              Dave
tagline:            on GitHub Pages
description:        Miscellaneous, mostly work related notes.
url:                http://datadavev.github.io
paginate:           10
paginate_path:      "/page:num"

author:
  name:             Dave Vieglais
  url:              https://ku.edu/~vieglais
  email:            

# GitHub Pages / Jekyll configuration
markdown: pandoc
pandoc:
  extensions:
    - smart
    - mathjax
markdown_ext:       markdown,md
encoding:           utf-8

kramdown:
  input: GFM
baseurl:            ''
permalink:          /:year:month:day-:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       posts
