# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl: 
title: Dave's Notes
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: Absence of evidence is not evidence of absence
author: Dave Vieglais
email: dave [dot] vieglais [at] gmail
description: Notes on various topics 
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: America/NewYork
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md', 'page']
post:
  template: _post.txt
  extension: md
#page:
#  template: _page.txt
#  extension: md
git:
  branch: src