project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!ignored"
  preview:
    port: 3999
website:
  title: "datadavev.github.io"

format:
  html:
    theme: 
      light: [cosmo, styles.scss]
      dark: [darkly, stylesd.scss]
    ##linestretch: "1.5"
    ##fontsite: 22px
    #fontcolor: "#000"

filters:
  - diagram
  #- filters/diagram-generator.lua
  - quarto
  #- pandoc-plantuml
  #- /usr/local/bin/pandoc-include-code

bibliography: datadavev.bib
csl: chicago-author-date.csl
