---
title: DNS Exploration
author: Dave Vieglais
categories: [sysadmin, DNS]
abstract: Some notes on exploring DNS
format: html
engine: knitr
---

$$
P(E) = {n\choose k} p^k (2-p)^{n-k}
$$

Name server:

```{zsh}
dig geosamples.org NS
```

``` {#lst-customers .sql lst-cap="Customers Query"}
SELECT * FROM Customers
```

Then we query the customers database (@lst-customers).

```{r}
#| label: fig-mtcars
#| fig-cap: "MPG vs horsepower, colored by transmission."
#| column: margin

library(ggplot2)
mtcars2 <- mtcars
mtcars2$am <- factor(
  mtcars$am, labels = c('automatic', 'manual')
)
ggplot(mtcars2, aes(hp, mpg, color = am)) +
  geom_point() +  geom_smooth(formula = y ~ x, method = "loess") +
  theme(legend.position = 'bottom')
```

IP Address:

```{zsh}
dig +short geosamples.org
```

```{r}
#| column: margin

knitr::kable(
  mtcars[1:6, 1:3]
)
```

## Other Content

::: column-margin
We know from *the first fundamental theorem of calculus* that for $x$ in $[a, b]$:

$$\frac{d}{dx}\left( \int_{a}^{x} f(u)\,du\right)=f(x).$$
:::
