---
title: The demise of Empathy
---

*Empathy*: the action of understanding, being aware of, being sensitive to, and vicariously experiencing the feelings, thoughts, and experience of another.

"The fundamental weakness of Western civilization is empathy.”
Elon Musk

“In my work with the defendants [at Nuremberg], I was searching for the nature of evil and I now think I have come close to defining it. A lack of empathy. It’s the one characteristic that connects all the defendants, a genuine incapacity to feel with their fellow men.”

— Captain Gustave Gilbert, the US army psychologist assigned to observe the Nazi defendants at the Nuremberg trials.

---

A strong sense of empathy may have a deliterious effect over the longer term since showing empathy for those that do not mean they continue. Instead of being shunned and shut out from society, they continue to voice, and the empathetic rulers allow it, since it's their nature. The result could be the decline or even demise of empathy.

