---
title: Driveway Surfacing
author: Dave Vieglais
subtitle: How much gravel do I need?
categories: [living, infrastructure]
reference-location: margin
format:
  html:
    code-fold: true
---

Estimating materials needed for a simple gravel road, like my driveway.

A gravel road typically has three components: a layer of geotextile to prevent mixing the base with the substrate, a base layer of about 2" crushed rock to provide a foundation, and a surface layer of material that develops a hard surface. Each of the layers is 4 to 8" or so. A driveway will typically be about 12' wide, and the surface must be sloped to prevent water pooling.

Gravel is generally ordered by weight (since the yards use scales rather than buckets). A ton of crushed rock / gravel is typically about $1.4 ton.yd^{-3}$. A dump truck generally holds 22 ton, which equates to 15.7 yd. Crusher run includes the fines, and this is usally a bit heavier and variable by moisture content (best to order after a dry spell).

A one inch layer on a 12' wide roadway is one cubic foot per foot of roadway. Since one cubic yard is 27 ft^3, one yard^3 will cover 27 ft, and one truck will cover about 424 ft at a one inch depth, 106ft at 4", and 71ft at 6".

The formula for tons per ft length per inch thckness is:

$$
\begin{eqnarray}
t &=& length \times 12 \times \frac{thick}{12 \times 27} \times 1.4 \\
&=& length \times thick \times 0.05185 \\
&=& \frac{length \times thick}{19.28}
\end{eqnarray}
$$

Assuming $36 / ton, the cost per foot is:
$$
\begin{eqnarray}
cost &=& \frac{length \times thick}{19.28} \times 36 \\
&=& length \times thick \times 1.867
\end{eqnarray}
$$

This comes out to around $1500 per one hundred feet of driveway at 8" thick, plus machine time and geotextile.

```{python}

```
