---
title: Innate Tendencies
subtitle: Behavior driven by innate tendencies.
author: Dave Vieglais
categories: [behavior]
reference-location: margin
---

What are the fundamental dimensions of behavior? 

People tend to prefer additive rather than subtractive changes (@adamsPeopleSystematicallyOverlook2021). 

People habitually seek order and consistency (@brothertonSuspiciousMindsWhy2015). This desire for order may conflict with our preference for additive changes.

Humans are quite good at finding patterns. So much so, that we can find patterns where there are none (@friedmanWhyHumansAre2020). The tendency to find patterns where none exist can be exacerbated by a situation of disorder and conflict (@brothertonSuspiciousMindsWhy2015).

Some people have a willingness to believe in unseen, intentional forces and an attraction to Maichean narratives^[A tendency to look at things as having two sides that are opposed.], @oliverConspiracyTheoriesParanoid2014.

When overwhelmed with information we have a tendency to simplify by reliance on paranormal or supernatural beliefs. It is something of a coping mechanism. 

Paranormal belief scale: A belief in ghosts or extra sensory perception. See @louisianatechuniversityRevisedParanormalBelief2004

Supernatural belief scale: A belief in angels or the Devil (@jongFearDeathSupernatural2013; @bluemkeSupernaturalBeliefScale2017).

Creating a to-do list can result in more mind-wandering, suggesting that cues related to personal goals and concerns can trigger mind-wandering in a habitual stimulus-response-like fashion (@zedeliusMindWanderingMore2018a, pp366). However, @masicampoConsiderItDone2011 found that making a plan for addressing the unresolved goals (rather than merely listing them) can free us from this kind of habitual mind wandering. Instead of merely listing things to be done, make the effort to determine how and when they are to be done, that is, plan the outcome ready for execution. 

---

In chaotic situations, a tendency to follow those appearing to be more in control. (Is this a Trump control factor - create chaos and appear to be on top of the situation)